config/routes.rb
Word::Application.routes.draw do
  resources :translates

  

end

app/models/translate.rb
class Translate < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/translates_controller.rb
class TranslatesController < ApplicationController
  before_action :set_translate, only: [:show, :edit, :update, :destroy]

  # GET /translates
  # GET /translates.json
  def index
    @translates = Translate.all
  end

  # GET /translates/1
  # GET /translates/1.json
  def show
  end

  # GET /translates/new
  def new
    @translate = Translate.new
  end

  # GET /translates/1/edit
  def edit
  end

  # POST /translates
  # POST /translates.json
  def create
    @translate = Translate.new(translate_params)

    respond_to do |format|
      if @translate.save
        format.html { redirect_to @translate, notice: 'Translate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @translate }
      else
        format.html { render action: 'new' }
        format.json { render json: @translate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /translates/1
  # PATCH/PUT /translates/1.json
  def update
    respond_to do |format|
      if @translate.update(translate_params)
        format.html { redirect_to @translate, notice: 'Translate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @translate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /translates/1
  # DELETE /translates/1.json
  def destroy
    @translate.destroy
    respond_to do |format|
      format.html { redirect_to translates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_translate
      @translate = Translate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def translate_params
      params.require(:translate).permit(:brasileira, :inglesa, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/translates_helper.rb
module TranslatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Word</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/translates/_form.html.erb
<%= form_for(@translate) do |f| %>
  <% if @translate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@translate.errors.count, "error") %> prohibited this translate from being saved:</h2>

      <ul>
      <% @translate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brasileira %><br>
    <%= f.text_field :brasileira %>
  </div>
  <div class="field">
    <%= f.label :inglesa %><br>
    <%= f.text_field :inglesa %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/translates/edit.html.erb
<h1>Editing translate</h1>

<%= render 'form' %>

<%= link_to 'Show', @translate %> |
<%= link_to 'Back', translates_path %>

app/views/translates/index.html.erb
<h1>Translates</h1>

<table>
  <thead>
    <tr>
      <th>Brasileira</th>
      <th>Inglesa</th>
      <th>Data</th>

    </tr>
  </thead>

  <tbody>
    <% @translates.each do |translate| %>
      <tr>
        <td><%= translate.brasileira %></td>
        <td><%= translate.inglesa %></td>
        <td><%= translate.data %></td>
        <td><%= link_to 'Show', translate %></td>
        <td><%= link_to 'Edit', edit_translate_path(translate) %></td>
        <td><%= link_to 'Destroy', translate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Translate', new_translate_path %>

app/views/translates/new.html.erb
<h1>New translate</h1>

<%= render 'form' %>

<%= link_to 'Back', translates_path %>

app/views/translates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brasileira:</strong>
  <%= @translate.brasileira %>
</p>

<p>
  <strong>Inglesa:</strong>
  <%= @translate.inglesa %>
</p>

<p>
  <strong>Data:</strong>
  <%= @translate.data %>
</p>

<%= link_to 'Edit', edit_translate_path(@translate) %> |
<%= link_to 'Back', translates_path %>